### ISSUE TITLE
Create route for getting analysis data

### ISSUE THREAD

**Issue by yoavrichter30** [RevisarAI/RevisarAI#15]
## Description
For the home page we need to implement routes for getting the analysis data of the dashboard - 

- Data source disterbution.
- Sentiment over time.
- Trending keywords.
- Weekly action items - Title, Done?, moreData.

## DoD

- [ ] We have route for getting the data needed for the home page.

**Comment by chenyair** [comment]
@yoavrichter30 Weekly action items should be in a different issue
