### ISSUE TITLE
Create Swagger for `ReviewsLoader`

### ISSUE THREAD

**Issue by yoavrichter30** [RevisarAI/RevisarAI#28]
## Description
We want to create swagger API doc for our apis.

## DoD

- [ ] We have swagger doc for `ReviewsLoader`.

**Comment by satokenta940** [comment]
If you're looking to generate API documentation that's user-friendly and easy to navigate, [Apidog ](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1)is indeed a very good option. 
﻿ 
﻿
