### ISSUE TITLE
Create route `/reviews` in ReviewsReceiver

### ISSUE THREAD

**Issue by yoavrichter30** [RevisarAI/RevisarAI#5]
## Description
In ReviewsReceiver we need to have a route for pushing raw data, so a route `/reviews` probably `POST`.
We will receive the data itself in JSON format (or Avro/Parquet/Bson we need to decide together) alongside user data.
Furthermore - the logic of the route should be writing to our MQ.

## DoD

- [x]  We have a route for pusing data into the ReviewsReceiver.
- [ ] The data is written to our MQ.

**Comment by Shaked-abdu** [comment]
[](https://github.com/RevisarAI/RevisarAI/pull/31)

**Comment by Shaked-abdu** [comment]
#31
