### ISSUE TITLE
Move generate api key route outside from Reviews Receiver

### ISSUE THREAD

**Issue by Shaked-abdu** [RevisarAI/RevisarAI#73]
## Description
In the current situation the route to genetare an api key is public.
Think of better solution for issue an api-key.

## DoD
- [x] We have secured route to issue an api-key

**Comment by Shaked-abdu** [comment]
In my opinion we can issue an api-key in the backend (while client register).
What do you think?
@yoavrichter30 @chenyair @liadyacobi

**Comment by liadyacobi** [comment]
How are we going to give the api key to the client in the UI when he registers?
We can't store the plain api key so we can only show it to him once.
I think it's better we manage API keys in the settings tab where the user will also be able to keep track of his keys and create a new one.
