### ISSUE TITLE
Implement REST GET route for weekly action items

### ISSUE THREAD

**Issue by liadyacobi** [RevisarAI/RevisarAI#80]
## Description
The weekly action items are stored in the DB but are not accessible through REST API via the backend

## DoD
A GET route for action-items returns the business weekly action items

**Comment by liadyacobi** [comment]
@chenyair 
Do you think we should implement this route with pagination?

**Comment by chenyair** [comment]
> @chenyair 
> 
> Do you think we should implement this route with pagination?

No I think this route should return the latest action items which is always 5
